BUFFER_SIZE = int(1e5)  # replay buffer size
BATCH_SIZE = 128  # minibatch size
GAMMA = 0.99  # discount factor
TAU = 3e-1  # for soft update of target parameters
LR_ACTOR = 1e-4  # learning rate of the actor
LR_CRITIC = 2e-4  # learning rate of the critic
WEIGHT_DECAY = 0  # L2 weight decay
EPSILON_DECAY = 1  # decay factor for exploration rate
LEARN_NUM = 4  # number of learning passes
UPDATE_EVERY = 2  # Frequency of target networks update
RANDOM_SEED = 3  # Random seed
